# Generated by Django 5.2.5 on 2025-09-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voucher',
            table='orders_voucher',
        ),
        migrations.AlterModelTable(
            name='voucherredemption',
            table='orders_voucherredemption',
        ),
    ]
