# Generated by Django 5.1.6 on 2025-09-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_address_line_2_remove_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Hoàn tất'), ('PENDING', 'Đang xử lý'), ('FAILED', 'Thất bại'), ('CANCELED', 'Đã hủy'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=100),
        ),
    ]
