# Generated by Django 5.1.6 on 2025-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
